services:
  app:
    image: docker-registry.syscd.tech/board-games:latest
    build:
      context: .
      target: dev
    command: go run main.go
    ports:
      - 8080:8080
    volumes:
      - ./:/app
  bin:
    image: docker-registry.syscd.tech/board-games:latest
    build:
      context: .
    ports:
      - 8080:8080