version: '3'

env:
  REGISTRY: '{{.REGISTRY | default "docker-registry.syscd.tech"}}'

tasks:
  op-inject:
    cmds:
      - op inject --account=my.1password.com -f -i .env.op -o .env
  run:
    cmds:
      - go run ./cmd/server -c config.yaml
  cli:
    cmds:
      - go run ./cmd/cli -c config.yaml
  load:
    cmds:
      - 'curl -sS -X POST -H "Authorization: Bearer ${BOARDGAMES_TOKEN}" --data-binary @data/inventory.yaml http://localhost:8080/api/load'
  load-prd:
    cmds:
      - 'curl -sS -X POST -H "Authorization: Bearer ${BOARDGAMES_TOKEN}" --data-binary @data/inventory.yaml https://bg.monaddaydream.com/api/load'