apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "board-games.fullname" . }}-data
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.cache.storageClass }}
  resources:
    requests:
      storage: {{ .Values.cache.size }}
